[workspace]
members = ["dp-transform", "dp-pyo3", "soac-codegen"]
default-members = ["dp-transform", "dp-pyo3"]
# soac-runtime is standalone since its built to CLIF 
exclude = ["soac-runtime"]
resolver = "2"
